<?php

/**
 * Simple mutex API
 * Copyright 2012 droptable/murdoc
 */

namespace rrl\server;

function mutex_parse() {
  static $regex = '/^\s*((?:(?:\d{1,3}){4}|(?:\[[^\]]+)|\w+):(\d+)|(.*)\s*$/';
  
  if (!file_exists($path = __DIR__ . '/mutex.dat'))
    return;
    
  $mutex = []; 
  
  foreach (file($path) as $line) {
    if (empty($line) || $line[0] === '#')
      continue;
      
    if (!preg_match($regex, $line, $match))
      continue;
      
    $res = [ 'host' => $match[1], 'port' => (int) $match[2] ];
    
    foreach (explode(';', $match[3]) as $prop) {
      list ($name, $value) = explode('=', $prop, 2);
      $res[$name] = $value;
    }
    
    $mutex[] = $res;
  }
  
  return $mutex;
}

function mutex_update(array $data) {
  if (!file_exists(($path = __DIR__ . '/mutex.dat'))
    touch($path);
    
  $buff = '# server-mutex file' . PHP_EOL
    . '# do not edit this file!' . PHP_EOL . PHP_EOL
    . '# format is: host:port|pid=123;...';
  
  foreach ($data as $line) {
    $buff .= $line['host'] . ':' . $line['port'] . '|';
    
    foreach ($line as $name => $value) {
      if ($name === 'host' || $name === 'port')
        continue;
      
      $buff .= $name . '=' . $value . ';';
    }
  }
  
  file_put_contents($path, $buff);
}

